### ISSUE TITLE
Does this work replacing Library symbols with the same symbols in another Library?

### ISSUE THREAD

**Issue by ryanbelisle** [sonburn/symbol-swapper#1]
Let's say I have a COMPONENT library w/ 30+ icons.
In **Sketch File A** - I insert a ton of the shared icons into the document.

Tomorrow a decision is made to move the icons in the COMPONENT library into a separate ICONS library. 

Is it possible to select all the shared icon symbols pointing to the COMPONENT library to the ICONS library?

**Comment by sonburn** [comment]
Yes, this plugin will allow you to remap all the instances pointing to your original library, to the new library (as long as there is a symbol of the same name in the new library).
