### ISSUE TITLE
Not swapping nested symbols

### ISSUE THREAD

**Issue by tijmenvangurp** [sonburn/symbol-swapper#10]
Dear Sonburn,

First of all amazing plugin. I think you already provided me with some helpful answers on sketchplugins.com Hope you are able to help me on this bug as well and in the meantime improve your plugin.

I prepared a sketch file and video demonstrating the issue I found. 

[https://www.dropbox.com/s/ef294ww3y1hyb3y/nested-symbols-issue.zip?dl=0](https://www.dropbox.com/s/ef294ww3y1hyb3y/nested-symbols-issue.zip?dl=0)

- a symbol from a library if it contains a nested symbol it does not swap
- swapped symbols remain in the file as "normal" symbols, and are not cleaned up

possible causes

`changeInstanceToSymbol`
Does not update the nested symbols

`updateOverridesWithObjectIDMap`
Does not update ID's of nested symbols

`removeFromParent`
Changed instances are not removed from the document if they are unused.

Let me know if you need any more input.

**Comment by tijmenvangurp** [comment]
@sonburn Any thoughts on this?

**Comment by sonburn** [comment]
@tijmenvangurp, sorry for the delayed response.

If the symbol containing nested symbol(s) is a local symbol, meaning it exists on the Symbols page (or in the document somewhere), then the nested symbol _will_ be swapped with Symbol Swapper.

If the symbol containing nested symbol(s) is a foreign symbol, meaning it exists in a Library, then the local version of symbol actually exists in the foreign symbols object, which I cannot modify.

The only way to achieve the illusion that a nested symbol within a foreign symbol has been swapped would be to simply override the nested symbol with the desired symbol. Despite the fact that this is technically not a swap, it would be complicated as well, as I would need to check to make sure there is not another override already in place for that nested symbol.

I will think on this a bit more though.

**Comment by tijmenvangurp** [comment]
Hey @sonburn Thanks for your answer. I think the use case that I have is quite specific. Will let you know if I find an answer on this! I am fine if you close this issue as this is probably not the intent of your plugin.
