### ISSUE TITLE
Window height (display a lot of libraries)

### ISSUE THREAD

**Issue by dumptiness** [sonburn/symbol-swapper#15]
It's a recurrent problem I have but the plugin is unusable when there's a lot of libraries involved.

It can only display as much libraries as it can depending on the height of the monitor. I have to select the wider scale to gain a spot and then there's just no more options. **Can't it be scrollable?**
Also, the buttons appeared on the back so the selects are displayed on top which is problematic.

<img width="422" alt="not enough space" src="https://user-images.githubusercontent.com/15635024/43126566-51080a46-8f2d-11e8-8db4-87001f1ec44e.png">

**Comment by sonburn** [comment]
@dumptiness Thanks for bringing this to my attention... I will improve this.

**Comment by dumptiness** [comment]
Thanks for the quick reply!
This plugin literally saves me hours of work so good job for developing it 👍

**Comment by sonburn** [comment]
@dumptiness The library swapping window is now scrollable in version 0.12. Please update and let me know what you think!
