### ISSUE TITLE
Replacing Library symbols with the same symbols in another Library

### ISSUE THREAD

**Issue by justinspencer** [sonburn/symbol-swapper#16]
I'm trying to use Symbol Swap Libraries so I can replace all the symbols from Library A with the same (named) symbols in Library B. The dialogue box tells me that the symbols have been swapped and the path to new library changes however the symbols remain unchanged.

Symbol Swap Selections seems to work OK but it won't include overrides

Am I doing something wrong?

Sketch 51.1
High Sierra 10.13.6

**Comment by sonburn** [comment]
@justinspencer do you have an indicator to update symbols after running the plugin?

**Comment by justinspencer** [comment]
This is all I get.

![screen shot 2018-07-31 at 2 14 47 pm](https://user-images.githubusercontent.com/936597/43437396-292fd6f8-94cc-11e8-872c-13fb5225c651.png)

**Comment by justinspencer** [comment]
Yep all good. Works perfectly. Thanks

**Comment by justinspencer** [comment]
https://vimeo.com/282438828

**Comment by sonburn** [comment]
@justinspencer Vimeo link doesn't seem to resolve, but glad the plugin is working for you! I should really let the user know, after running Symbol Swapper on libraries, that they may need to update their symbols after running the plugin.

**Comment by justinspencer** [comment]
@sonburn I agree, might be worth adding a little note to let people know that they need to update their symbols. Thanks again for your help. @agnethesh yep as long as the Symbols are the same name it's all good. The screen recording I did should work now. https://vimeo.com/282438828
