### ISSUE TITLE
Will it support libraries?

### ISSUE THREAD

**Issue by willowbrae** [sonburn/symbol-swapper#3]
Will it support libraries?

It is a nightmare right now in Sketch to change all of the symbols from local to the library ones. This plugin could save a ton of hours if we could swap all the symbols with the same name to the selected one (or all with the same name).

**Comment by sonburn** [comment]
Yes, it supports libraries. 🙂

**Comment by willowbrae** [comment]
You just saved my life :)
Do you plan to do "one click > replace all" ?

**Comment by sonburn** [comment]
Yes, it's likely the next update.
