### ISSUE TITLE
Plug in doesn't update

### ISSUE THREAD

**Issue by tzekin** [sonburn/symbol-swapper#32]
Sketch update plug-in dialog says a new version 0.16 is available but it doesn't download. Manually installing the latest version keeps telling me there is an update.

I have seen this problem with many plug ins the problem that do not report the correct version at all places in the code.

**Comment by lmjabreu** [comment]
It appears that the version number in manifest.json wasn't updated to 0.16.

**Comment by tzekin** [comment]
Indeed

**Comment by sonburn** [comment]
@tzekin, @lmjabreu, you guys are absolutely right, I missed the version in the Manifest. Just committed that, thanks for bringing it to my attention!

**Comment by lmjabreu** [comment]
No worries, thanks a lot for your work!
