### ISSUE TITLE
Symbol Swapper Library not Working

### ISSUE THREAD

**Issue by HsiehYulin** [sonburn/symbol-swapper#33]
There is a problem since ver. 0.15, Symbol Swapper Library is not working.
I don't use local symbol, all profile is link to library, when i want to swap from A library to B library, it can't work. But i try Swap Selection, it can work.

I like this plugin very much and use it very often, wish you can fix this problem.
Thank you. #

**Comment by Luciea** [comment]
Me too 😢

**Comment by uwings** [comment]
插眼等更……

**Comment by sonburn** [comment]
@HsiehYulin, @Luciea, @uwings thank you for bringing this to my attention, sorry you are having issues with the plugin. I just published an update which might fix the issue, could you please download and try version 0.17?

**Comment by HsiehYulin** [comment]
＠sonburn thank you for repairing this problem, i already update to version 0.17 and it works, it means a lot to me!!
