### ISSUE TITLE
Symbol Swapper is showing libraries of old / removed symbols

### ISSUE THREAD

**Issue by louiesolomon** [sonburn/symbol-swapper#34]
Symbol swapper is showing deleted symbols and libraries. In the included screenshot, I have 3 symbols in my Sketch file, all of which are from `TEST-ATOMS-NIGHT`. The other libraries have been removed or deleted.

<img width="973" alt="Screen Shot 2019-04-22 at 2 30 44 PM" src="https://user-images.githubusercontent.com/975080/56521809-6da3ae80-650b-11e9-8073-ace30b4c6d71.png">

**Comment by sonburn** [comment]
@louiesolomon If a symbol was in use in your document, but no longer, Sketch will automatically purge the unused symbol from your document when it is saved. Can you confirm this is still occurring after you have saved your document?

**Comment by louiesolomon** [comment]
I'm not sure what caused the issue, but I'm having trouble recreating it now. I've attached the demo files if you'd like to see the issue.
[ATOMS TESTING.zip](https://github.com/sonburn/symbol-swapper/files/3108496/ATOMS.TESTING.zip)

**Comment by sonburn** [comment]
@louiesolomon I have a feeling it's because the file has been saved now, and the inherent action Sketch takes to purge unused symbols in the foreign symbol cache has occurred. Since you can no longer reproduce the issue, mind if I close the ticket?

**Comment by louiesolomon** [comment]
Go for it. Thanks for the help.
