### ISSUE TITLE
Symbol Swapper (verion 0.16)  library not working in the Sketch 54.1 

### ISSUE THREAD

**Issue by LenaAlyanova** [sonburn/symbol-swapper#35]
Hi, 
I updated my Sketch to 54.1 version  and I have some trouble with plugin Symbol Swapper.
I can not swapp libraries, if I have  many libraries in my list  ( in the Sketch).
Can you help me, please?

**Comment by nikolayzaytsev** [comment]
Confirmed. Have the same issue.

**Comment by sonburn** [comment]
@LenaAlyanova, @nikolayzaytsev, thank you for bringing this to my attention, sorry you are having issues with the plugin. I just published an update which might fix the issue, could you please download and try version 0.17?

**Comment by nikolayzaytsev** [comment]
Thank you, @sonburn ! It works on my side now.

**Comment by LenaAlyanova** [comment]
> Thank you, @sonburn ! It works on my side now.

 Thank you, @sonburn !
