### ISSUE TITLE
Loosing overrides in mass swap

### ISSUE THREAD

**Issue by willowbrae** [sonburn/symbol-swapper#4]
When I swap symbol and its copies with the one from a library only the first one keeps its overwrites. _Swap siblings & overrides of selected instances_ is on. 
Sketch when swapping local symbols has similar problem - is it them?

**Comment by sonburn** [comment]
There _are_ some quirks with deeply nested overrides, but simple overrides should have no problems. Overrides are generally very brittle though. Sometimes, reapplying the override symbol (in the case of a nested override) will correct the issue, other times I have had to manually correct the problems. I am researching improvements that can be made.
