### ISSUE TITLE
Plugin not working in Sketch 61

### ISSUE THREAD

**Issue by terjin** [sonburn/symbol-swapper#40]
No longer shows the success prompt when symbols are swapped nor does it show which symbols couldn't be swapped.

Any ideas on a fix or other plugins that could help?

**Comment by sonburn** [comment]
@terjin I finally found some time to make some long overdue plugin updates, and I fixed this issue. Can you download version 0.20 and let me know if your experience is improved?

**Comment by terjin** [comment]
@sonburn just tested, its working now!

Thank you so much @sonburn

**Comment by sonburn** [comment]
Thank you for confirming, and thank you for using my plugin!
