### ISSUE TITLE
'Let me choose' option uses the wrong symbol

### ISSUE THREAD

**Issue by Northernfern** [sonburn/symbol-swapper#46]
When selecting which symbol to use for replacement with 'let me choose', the function does not use the selected symbol but a different, wrong one. Why is that?

**Comment by jrapert** [comment]
Same here. I need this to work. I have too many to replace. Help!

**Comment by sonburn** [comment]
@Northernfern Apologies, there was an issue with the last version, which I finally got a chance to resolve. Could you please try version 0.21 which I just published?

**Comment by sonburn** [comment]
The issue had to do with missing and disabled libraries not being removed from the list of available libraries, this is why the results were offset at times, or other times the plugin would fail. Version 0.21 was a step in the right direction but there was still another issue which I have resolved in 0.22.

**Comment by Northernfern** [comment]
Great, thanks!
