### ISSUE TITLE
Request - Enable swapping non-symbols and retain dimensions

### ISSUE THREAD

**Issue by RaphyRaph** [sonburn/symbol-swapper#5]
When updating a file with a new component, you sometimes need to swap normal groups to a symbol. You can already do that using the "replace layer with" command, but that doesn't retain the dimensions of the layer you're trying to replace, like it would on a symbol.

**Comment by sonburn** [comment]
@RaphyRaph I think Sketch 48 will do this for you now - https://www.sketchapp.com/updates/#version-48

"When replacing a layer with a Symbol, the Symbol now inherits the same size as the previous layer"
