### ISSUE TITLE
Scrolling Issue on v72

### ISSUE THREAD

**Issue by custa1200** [sonburn/symbol-swapper#58]
Hi I wrote this up on the wrong plugin (symbol-finder), so here goes in the right spot. When I go to the UI for Symbol swapper I am unable to scroll to the bottom of the list. I can kinda get to it if I am scrolling down and it is rubber banding while I click on the just peeking out select list. Have included a gif
![CleanShot 2021-05-12 at 13 57 36](https://user-images.githubusercontent.com/161224/117916400-705be100-b32a-11eb-887a-e8188271ddab.gif)

**Comment by sonburn** [comment]
@custa1200 I finally got a chance to fix this issue, please update to the latest version and let me know if it works for you.

**Comment by custa1200** [comment]
Fixed
