### ISSUE TITLE
Doesn't swap symbols with changed naming

### ISSUE THREAD

**Issue by RaphyRaph** [sonburn/symbol-swapper#6]
With Sketch 48, I assume Symbols now have some kind of unique ID to be able to copy paste between files. Is there a way symbol swapper could use that ID as well? I have a lot of cases where symbols have been detached, renamed in the master, and now they can't be swapped unless you select each symbol manually, which is very time consuming.

**Comment by tijmenvangurp** [comment]
+ one for swapping based on symbolID see https://github.com/BohemianCoding/SketchAPI/blob/develop/docs/SymbolMaster.md

**Comment by sonburn** [comment]
@RaphyRaph and @tijmenvangurp, sorry it's taken so long to respond...

Symbol Swapper only looks for a symbol of the same name. You would have to use the Symbol Swap Selections portion of the plugin to swap the selected symbol (and siblings) with any symbol from any library.

I will consider an enhancement to allow for matching names and IDs. Thank you for the feedback and for using Symbol Swapper.

**Comment by sonburn** [comment]
@RaphyRaph, @tijmenvangurp, I just published an update to address some Sketch 50 things, and in this update you will find an option to swap symbols by ID. Can you give it a spin and let me know if it's working as you would expect?

**Comment by RaphyRaph** [comment]
thxxx! I'll give it a try

**Comment by mapper44** [comment]
Im finding once i swap the symbol from the local symbol to the external symbol, the instances where its used are not updated and instead im finding lots of 'missing symbol' text stamped across designs... I thought the intention with this plugin was to replace a local symbol with an external symbol with the changes reflected across the file where that symbol is used?  Can someone please clarify?

**Comment by sonburn** [comment]
@mapper44 Is this your experience with all libraries, or just one particular library?

**Comment by sonburn** [comment]
Just closing the loop here... recent updates to Symbol Swapper now allow you to swap individual symbols or whole libraries, using symbol names or symbol object IDs. Will now close this issue.
