### ISSUE TITLE
Symbol Swap Libraries not finding symbol masters of the same name in different libraries

### ISSUE THREAD

**Issue by craveytrain** [sonburn/symbol-swapper#8]
I'm having issues with the swap library functionality. I have 2 libraries that have symbol masters of the same names (they are generated from the same source code). I have also have a Sketch file where I am referencing the masters from 1 of those libraries. When I try to swap them, it tells me they weren't found in the new library.

Is it keying on something different than the name of the symbol master's name?

Any help would be greatly appreciated.

Thank you.

**Comment by sonburn** [comment]
@craveytrain Symbol Swapper definitely only looks for a symbol of the same name. Is this still an issue you are experiencing? If so, are you able to provide an example file as I have not run into this issue?

**Comment by sonburn** [comment]
Closing due to lack of response.
