### ISSUE TITLE
Feature Request - Ignored Symbols

### ISSUE THREAD

**Issue by WalleyeAU** [sonburn/symbol-swapper#9]
Hi Jason!

I was hoping to get a feature enhancement into your backlog. When you do a symbol swap to another library, sometimes a symbol gets ignored because it doesn't exist in the new library. What would be really helpful is an indication of which symbol it is.

Ideally, something like your Symbol Instance Locator dialog to show and access multiple ignored symbols. What would be amazing is both Locator and Swapper would be one plugin 👍 

Amazing work BTW, you've saved me and my extremely complex nested Sketch Libraries!!

Cheers

Chris

![ignored_symbol_message](https://user-images.githubusercontent.com/19472913/37852262-0db46fb6-2f36-11e8-9418-080300578249.png)

**Comment by sonburn** [comment]
@WalleyeAU Thank you for the feedback and suggestion, and thanks for using my plugins. I will consider this as an enhancement.

**Comment by sonburn** [comment]
@WalleyeAU, please check out the latest version (0.11) as I have added a report of ignored symbols (as well as the ability to swap all symbols from current document to library).
